//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ZPad.RC
//


#define IDD_ABOUTBOX				100
#define IDR_MAINFRAME				128
//#define IDR_ZPADTYPE	129

#define IDZPAD_FILE_NEW						200
#define IDZPAD_FILE_OPEN					201
#define IDZPAD_FILE_BROWSE					202
#define IDZPAD_FILE_REVERT					203
#define IDZPAD_FILE_SAVE					204
#define IDZPAD_FILE_SAVEAS					205
#define IDZPAD_FILE_SAVECOPY				206
#define IDZPAD_FILE_READONLY				207
#define IDZPAD_FILE_NEWWINDOW				208
#define IDZPAD_FILE_NEWWINDOW2				209
#define IDZPAD_FILE_LAUNCH					210
#define IDZPAD_FILE_OPENWITH				211
#define IDZPAD_FILE_RUN						212
#define IDZPAD_FILE_PAGESETUP				213
#define IDZPAD_FILE_PRINT					214
#define IDZPAD_FILE_PROPERTIES				215
#define IDZPAD_FILE_CREATELINK				216
#define IDZPAD_FILE_OPENFAV					217
#define IDZPAD_FILE_ADDTOFAV				218
#define IDZPAD_FILE_MANAGEFAV				219
#define IDZPAD_FILE_RECENT					220
#define IDZPAD_FILE_EXIT					221

#define IDZPAD_ENCODING_ANSI				230
#define IDZPAD_ENCODING_UNICODE				231
#define IDZPAD_ENCODING_UNICODEREV			232
#define IDZPAD_ENCODING_UTF8				233
#define IDZPAD_ENCODING_UTF8SIGN			234
#define IDZPAD_ENCODING_SELECT				235
#define IDZPAD_ENCODING_RECODE				236
#define IDZPAD_ENCODING_SETDEFAULT			237

#define IDZPAD_LINEENDINGS_CRLF				240
#define IDZPAD_LINEENDINGS_LF				241
#define IDZPAD_LINEENDINGS_CR				242
#define IDZPAD_LINEENDINGS_SETDEFAULT		243

#define IDZPAD_EDIT_UNDO					300
#define IDZPAD_EDIT_REDO					301
#define IDZPAD_EDIT_CUT						302
#define IDZPAD_EDIT_COPY					303
#define IDZPAD_EDIT_PASTE					304
#define IDZPAD_EDIT_FIND					305
#define IDZPAD_EDIT_REPLACE					306
#define IDZPAD_EDIT_COPYALL					307
#define IDZPAD_EDIT_COPYADD					308
#define IDZPAD_EDIT_SWAP					309
#define IDZPAD_EDIT_CLEAR					310
#define IDZPAD_EDIT_CLEARCLIPBOARD			311
#define IDZPAD_EDIT_SELECTALL				312
#define IDZPAD_EDIT_MOVELINEUP				313
#define IDZPAD_EDIT_MOVELINEDOWN			314
#define IDZPAD_EDIT_DUPLICATELINE			315
#define IDZPAD_EDIT_CUTLINE					316
#define IDZPAD_EDIT_COPYLINE				317
#define IDZPAD_EDIT_DELETELINE				318
#define IDZPAD_EDIT_COLUMNWRAP				319
#define IDZPAD_EDIT_SPLITLINES				320
#define IDZPAD_EDIT_JOINLINES				321
#define IDZPAD_EDIT_JOINLINESEX				322
#define IDZPAD_EDIT_INDENT					323
#define IDZPAD_EDIT_UNINDENT				324
#define IDZPAD_EDIT_ENCLOSESELECTION		325
#define IDZPAD_EDIT_SELECTIONDUPLICATE		326
#define IDZPAD_EDIT_PADWITHSPACES			327
#define IDZPAD_EDIT_STRIP1STCHAR			328
#define IDZPAD_EDIT_STRIPLASTCHAR			329
#define IDZPAD_EDIT_TRIMLINES				330
#define IDZPAD_EDIT_COMPRESSWS				331
#define IDZPAD_EDIT_MERGEBLANKLINES			332
#define IDZPAD_EDIT_REMOVEBLANKLINES		333
#define IDZPAD_EDIT_MODIFYLINES				334
#define IDZPAD_EDIT_ALIGN					335
#define IDZPAD_EDIT_SORTLINES				336
#define IDZPAD_EDIT_CONVERTUPPERCASE		337
#define IDZPAD_EDIT_CONVERTLOWERCASE		338
#define IDZPAD_EDIT_INVERTCASE				339
#define IDZPAD_EDIT_TITLECASE				340
#define IDZPAD_EDIT_SENTENCECASE			341
#define IDZPAD_EDIT_CONVERTSPACES			342
#define IDZPAD_EDIT_CONVERTTABS				343
#define IDZPAD_EDIT_CONVERTSPACES2			344
#define IDZPAD_EDIT_CONVERTTABS2			345
#define IDZPAD_EDIT_INSERT_TAG				346
#define IDZPAD_EDIT_INSERT_ENCODING			347
#define IDZPAD_EDIT_INSERT_SHORTDATE		348
#define IDZPAD_EDIT_INSERT_LONGDATE			349
#define IDZPAD_EDIT_INSERT_FILENAME			350
#define IDZPAD_EDIT_INSERT_PATHNAME			351
#define IDZPAD_EDIT_LINECOMMENT				352
#define IDZPAD_EDIT_STREAMCOMMENT			353
#define IDZPAD_EDIT_URLENCODE				354
#define IDZPAD_EDIT_URLDECODE				355
#define IDZPAD_EDIT_ESCAPECCHARS			356
#define IDZPAD_EDIT_UNESCAPECCHARS			357
#define IDZPAD_EDIT_CHAR2HEX				358
#define IDZPAD_EDIT_HEX2CHAR				359
#define IDZPAD_EDIT_FINDMATCHINGBRACE		360
#define IDZPAD_EDIT_SELTOMATCHINGBRACE		361
#define IDZPAD_EDIT_SELTONEXT				362
#define IDZPAD_EDIT_SELTOPREV				363
#define IDZPAD_EDIT_SAVEFIND				364
#define IDZPAD_EDIT_FINDNEXT				365
#define IDZPAD_EDIT_FINDPREV				366
#define IDZPAD_EDIT_REPLACENEXT				367
#define IDZPAD_EDIT_GOTOLINE				368

#define IDZPAD_VIEW_WRAP					400
#define IDZPAD_VIEW_ZOOMIN					401
#define IDZPAD_VIEW_ZOOMOUT					402
#define IDZPAD_VIEW_SCHEMES					403
#define IDZPAD_VIEW_SCHEMEC					404
#define IDZPAD_VIEW_USE2NDDEFAULT			405
#define IDZPAD_VIEW_SCHEMECONFIG			406
#define IDZPAD_VIEW_FONT					407
#define IDZPAD_VIEW_WORDWRAP				408
#define IDZPAD_VIEW_LONGLINEMARKER			409
#define IDZPAD_VIEW_SHOWINDENTGUIDES		410
#define IDZPAD_VIEW_SHOWWHITESPACE			411
#define IDZPAD_VIEW_SHOWEOLS				412
#define IDZPAD_VIEW_WORDWRAPSYMBOLS			413
#define IDZPAD_VIEW_MATCHBRACES				414
#define IDZPAD_VIEW_HILITECURRENTLINE		415
#define IDZPAD_VIEW_LINENUMBERS				416
#define IDZPAD_VIEW_MARGIN					417
#define IDZPAD_VIEW_RESETZOOM				418
#define IDZPAD_VIEW_TABSASSPACES			419
#define IDZPAD_VIEW_TABSETTINGS				420
#define IDZPAD_VIEW_WORDWRAPSETTINGS		421
#define IDZPAD_VIEW_LONGLINESETTINGS		422
#define IDZPAD_VIEW_AUTOINDENTTEXT			423
#define IDZPAD_VIEW_AUTOCLOSETAGS			424
#define IDZPAD_VIEW_REUSEWINDOW				425
#define IDZPAD_VIEW_STICKYWINPOS			426
#define IDZPAD_VIEW_ALWAYSONTOP				427
#define IDZPAD_VIEW_MINTOTRAY				428
#define IDZPAD_VIEW_TRANSPARENT				429
#define IDZPAD_VIEW_SINGLEFILEINSTANCE		430
#define IDZPAD_VIEW_CHANGENOTIFY			431
#define IDZPAD_VIEW_SHOWFILENAMEONLY		432
#define IDZPAD_VIEW_SHOWFILENAMEFIRST		433
#define IDZPAD_VIEW_SHOWFULLPATH			434
#define IDZPAD_VIEW_SHOWEXCERPT				435
#define IDZPAD_VIEW_NOESCFUNC				436
#define IDZPAD_VIEW_ESCMINIMIZE				437
#define IDZPAD_VIEW_ESCEXIT					438
#define IDZPAD_VIEW_SAVEBEFORERUNNINGTOOLS	439
#define IDZPAD_VIEW_NOSAVERECENT			440
#define IDZPAD_VIEW_NOSAVEFINDREPL			441
#define IDZPAD_VIEW_TOOLBAR					442
#define IDZPAD_VIEW_CUSTOMIZETB				443
#define IDZPAD_VIEW_STATUSBAR				444
#define IDZPAD_VIEW_SAVESETTINGS			445
#define IDZPAD_VIEW_SAVESETTINGSNOW			446
#define	IDZPAD_VIEW_SCHEME					447

#define ID_FILE_NEW_WINDOW			32771

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE	201
#define _APS_NEXT_CONTROL_VALUE		1000
#define _APS_NEXT_SYMED_VALUE		101
#define _APS_NEXT_COMMAND_VALUE		32775
#endif
#endif
